// GRE word bank
// w = word, p = part of speech, m = meaning, s = example sentence, f = related form (optional)
const WORDS = [
{w:"abate",p:"v",m:"to lessen in intensity",s:"The storm's fury began to abate by dawn.",f:"abatement (n)"},
{w:"aberrant",p:"adj",m:"deviating from the norm",s:"The scientist flagged the aberrant data point as an error."},
{w:"abeyance",p:"n",m:"temporary suspension",s:"The project was held in abeyance until funding arrived."},
{w:"abscond",p:"v",m:"to leave hurriedly and secretly",s:"The treasurer absconded with the club's funds."},
{w:"abstain",p:"v",m:"to hold oneself back voluntarily",s:"Two senators chose to abstain from the vote.",f:"abstinence (n)"},
{w:"abstruse",p:"adj",m:"difficult to understand",s:"The lecture on topology was too abstruse for most freshmen."},
{w:"accolade",p:"n",m:"an award or praise",s:"Her novel earned accolades from critics worldwide."},
{w:"acerbic",p:"adj",m:"sharp and biting in tone",s:"The critic was known for his acerbic film reviews."},
{w:"acquiesce",p:"v",m:"to accept reluctantly without protest",s:"He acquiesced to his boss's demands to avoid conflict.",f:"acquiescent (adj)"},
{w:"acrimony",p:"n",m:"bitterness or harshness",s:"The divorce proceedings were marked by acrimony.",f:"acrimonious (adj)"},
{w:"acumen",p:"n",m:"keen insight or judgment",s:"Her business acumen helped the startup thrive."},
{w:"adamant",p:"adj",m:"refusing to be persuaded",s:"She was adamant that the deadline could not move."},
{w:"admonish",p:"v",m:"to warn or reprimand mildly",s:"The teacher admonished the students for talking in class."},
{w:"adroit",p:"adj",m:"skillful and clever",s:"The negotiator was adroit at defusing tension."},
{w:"adulation",p:"n",m:"excessive praise or admiration",s:"The pop star basked in the crowd's adulation."},
{w:"aesthetic",p:"adj",m:"concerned with beauty",s:"The museum's renovation preserved its original aesthetic."},
{w:"affable",p:"adj",m:"friendly and easy to talk to",s:"The affable host made every guest feel welcome."},
{w:"aggrandize",p:"v",m:"to increase in power or reputation",s:"The dictator used propaganda to aggrandize himself."},
{w:"alacrity",p:"n",m:"eager readiness",s:"She accepted the challenge with alacrity."},
{w:"altruism",p:"n",m:"selfless concern for others",s:"His altruism led him to donate most of his income.",f:"altruistic (adj)"},
{w:"ambiguous",p:"adj",m:"open to multiple interpretations",s:"The contract's wording was frustratingly ambiguous."},
{w:"ambivalent",p:"adj",m:"having mixed feelings",s:"She felt ambivalent about accepting the new job."},
{w:"ameliorate",p:"v",m:"to make better",s:"New policies helped ameliorate the housing shortage."},
{w:"amiable",p:"adj",m:"friendly and pleasant",s:"Their amiable neighbor always waved hello."},
{w:"anachronism",p:"n",m:"something out of its proper time",s:"The knight's cellphone was an obvious anachronism in the film."},
{w:"analogous",p:"adj",m:"comparable in certain respects",s:"The heart's function is analogous to a pump."},
{w:"anarchy",p:"n",m:"absence of governing authority",s:"The collapse of the state plunged the region into anarchy."},
{w:"anecdote",p:"n",m:"a short personal story",s:"He opened his speech with a funny anecdote."},
{w:"animosity",p:"n",m:"strong hostility",s:"Years of animosity between the families finally ended."},
{w:"anomaly",p:"n",m:"something that deviates from the norm",s:"The telescope detected an anomaly in the star's brightness."},
{w:"antagonist",p:"n",m:"a person who opposes another",s:"The novel's antagonist is more compelling than its hero."},
{w:"antipathy",p:"n",m:"a deep-seated dislike",s:"He felt an instinctive antipathy toward dishonesty."},
{w:"apathy",p:"n",m:"lack of interest or concern",s:"Voter apathy led to record-low turnout.",f:"apathetic (adj)"},
{w:"appease",p:"v",m:"to pacify by satisfying demands",s:"The king tried to appease the rebels with land grants."},
{w:"apprehensive",p:"adj",m:"anxious about the future",s:"She felt apprehensive before her first solo flight."},
{w:"arbitrary",p:"adj",m:"based on random choice, not reason",s:"The fine seemed arbitrary and unrelated to the offense."},
{w:"arcane",p:"adj",m:"mysterious and known to few",s:"The manual was full of arcane technical jargon."},
{w:"ardent",p:"adj",m:"passionate and enthusiastic",s:"She is an ardent supporter of local libraries."},
{w:"arduous",p:"adj",m:"requiring great effort; difficult",s:"The arduous hike took ten hours to complete."},
{w:"articulate",p:"adj",m:"able to express ideas clearly",s:"The witness gave an articulate account of the accident."},
{w:"ascetic",p:"adj",m:"practicing severe self-discipline",s:"The monk lived an ascetic life with few possessions."},
{w:"aspersion",p:"n",m:"an attack on someone's reputation",s:"He cast aspersions on his rival's integrity."},
{w:"assiduous",p:"adj",m:"diligent and persistent",s:"Her assiduous note-taking impressed the professor."},
{w:"astute",p:"adj",m:"having sharp judgment",s:"The astute investor spotted the trend early."},
{w:"audacious",p:"adj",m:"boldly daring",s:"The heist required an audacious plan."},
{w:"austere",p:"adj",m:"severe or plain in appearance",s:"The monastery's austere rooms held only a bed and desk."},
{w:"autonomous",p:"adj",m:"self-governing; independent",s:"The region became fully autonomous after the treaty."},
{w:"avarice",p:"n",m:"extreme greed for wealth",s:"Avarice drove the merchant to cheat his partners.",f:"avaricious (adj)"},
{w:"aversion",p:"n",m:"a strong dislike",s:"She has an aversion to crowded spaces."},
{w:"banal",p:"adj",m:"boringly ordinary; unoriginal",s:"The film's dialogue felt banal and predictable."},
{w:"belie",p:"v",m:"to give a false impression of",s:"His calm tone belied his inner panic."},
{w:"belligerent",p:"adj",m:"hostile and aggressive",s:"The belligerent customer shouted at the staff."},
{w:"benevolent",p:"adj",m:"kind and generous",s:"The benevolent donor funded the entire wing."},
{w:"benign",p:"adj",m:"gentle or harmless",s:"The tumor was found to be benign."},
{w:"blasphemy",p:"n",m:"disrespectful speech about sacred things",s:"His remarks were considered blasphemy by the priests."},
{w:"bolster",p:"v",m:"to support or strengthen",s:"New evidence bolstered the prosecution's case."},
{w:"bombastic",p:"adj",m:"pompous in speech or writing",s:"The politician's bombastic speech impressed no one."},
{w:"boorish",p:"adj",m:"rude and ill-mannered",s:"His boorish behavior embarrassed the whole table."},
{w:"brevity",p:"n",m:"conciseness in speech or writing",s:"The editor praised the brevity of her report."},
{w:"buttress",p:"v",m:"to support or reinforce",s:"New data buttressed the researcher's hypothesis."},
{w:"cacophony",p:"n",m:"a harsh mixture of sounds",s:"The construction site was a cacophony of drills and horns."},
{w:"candid",p:"adj",m:"honest and straightforward",s:"She gave a candid answer despite the awkward question."},
{w:"capitulate",p:"v",m:"to surrender or give in",s:"After a long siege, the city finally capitulated."},
{w:"capricious",p:"adj",m:"unpredictable; impulsive",s:"The capricious weather ruined our picnic plans."},
{w:"castigate",p:"v",m:"to criticize severely",s:"The coach castigated the team for its sloppy defense."},
{w:"catalyst",p:"n",m:"something that triggers change",s:"The scandal was a catalyst for reform."},
{w:"caustic",p:"adj",m:"bitterly sarcastic; corrosive",s:"His caustic remarks left the room silent."},
{w:"censure",p:"v",m:"to formally criticize or condemn",s:"The senator was censured for misusing funds."},
{w:"chicanery",p:"n",m:"trickery or deception",s:"Voters grew tired of political chicanery."},
{w:"circuitous",p:"adj",m:"indirect and roundabout",s:"We took a circuitous route to avoid traffic."},
{w:"circumspect",p:"adj",m:"cautious and wary",s:"She was circumspect about sharing details with strangers."},
{w:"clairvoyant",p:"adj",m:"having insight beyond normal perception",s:"His clairvoyant prediction of the merger stunned analysts."},
{w:"clandestine",p:"adj",m:"secret or concealed",s:"They held a clandestine meeting outside the city."},
{w:"coalesce",p:"v",m:"to come together into one",s:"The scattered protests coalesced into a national movement."},
{w:"coerce",p:"v",m:"to force through pressure or threats",s:"He was coerced into signing the false confession.",f:"coercive (adj)"},
{w:"cogent",p:"adj",m:"clear and convincing",s:"She made a cogent argument for the new policy."},
{w:"cognizant",p:"adj",m:"aware or informed of something",s:"He was fully cognizant of the risks involved."},
{w:"coherent",p:"adj",m:"logical and consistent",s:"The essay needed a more coherent structure."},
{w:"commensurate",p:"adj",m:"proportionate in size or degree",s:"Her salary was commensurate with her experience."},
{w:"complacent",p:"adj",m:"self-satisfied and unconcerned",s:"The champions grew complacent after years of winning."},
{w:"compliant",p:"adj",m:"obedient; conforming to rules",s:"The factory became compliant with safety regulations."},
{w:"conciliatory",p:"adj",m:"intended to placate or pacify",s:"He offered a conciliatory gesture to end the feud."},
{w:"condone",p:"v",m:"to accept or overlook wrongdoing",s:"The company does not condone dishonest behavior."},
{w:"conflagration",p:"n",m:"a large, destructive fire",s:"The conflagration destroyed a dozen city blocks."},
{w:"congenial",p:"adj",m:"pleasant and friendly",s:"The office had a congenial atmosphere."},
{w:"connoisseur",p:"n",m:"an expert judge of taste",s:"He is a connoisseur of fine wine."},
{w:"conspicuous",p:"adj",m:"easily noticeable",s:"Her bright red coat made her conspicuous in the crowd."},
{w:"contentious",p:"adj",m:"causing disagreement",s:"Immigration remains a contentious political topic."},
{w:"contrite",p:"adj",m:"feeling regret for wrongdoing",s:"He offered a contrite apology to his teammates."},
{w:"conundrum",p:"n",m:"a confusing or difficult problem",s:"The budget shortfall posed a real conundrum."},
{w:"convoluted",p:"adj",m:"excessively complicated",s:"The instructions were so convoluted no one could follow them."},
{w:"corroborate",p:"v",m:"to confirm with evidence",s:"Witness testimony corroborated the timeline of events."},
{w:"credulous",p:"adj",m:"too ready to believe things",s:"The credulous investors fell for the obvious scam."},
{w:"cryptic",p:"adj",m:"mysterious or puzzling",s:"He left a cryptic note before disappearing."},
{w:"cursory",p:"adj",m:"hasty and superficial",s:"A cursory glance at the report missed the error."},
{w:"cynical",p:"adj",m:"distrustful of others' motives",s:"Years of scandal left voters cynical about politicians."},
{w:"dearth",p:"n",m:"a scarcity or lack",s:"There is a dearth of affordable housing downtown."},
{w:"debacle",p:"n",m:"a complete failure or disaster",s:"The product launch turned into a public debacle."},
{w:"debase",p:"v",m:"to lower in quality or value",s:"Counterfeit coins debase the currency's value."},
{w:"debilitate",p:"v",m:"to weaken severely",s:"The illness debilitated him for months."},
{w:"decorum",p:"n",m:"polite, proper behavior",s:"Guests were expected to maintain decorum at the ceremony."},
{w:"deference",p:"n",m:"respectful submission to another",s:"Junior staff showed deference to the director."},
{w:"deleterious",p:"adj",m:"harmful; damaging",s:"Smoking has deleterious effects on the lungs."},
{w:"delineate",p:"v",m:"to describe or outline precisely",s:"The contract clearly delineates each party's duties."},
{w:"demagogue",p:"n",m:"a leader who exploits popular prejudice",s:"Historians warned that the speaker was a classic demagogue."},
{w:"denounce",p:"v",m:"to publicly condemn",s:"The council denounced the violence at the rally."},
{w:"deride",p:"v",m:"to mock or ridicule",s:"Critics derided the film as amateurish."},
{w:"derivative",p:"adj",m:"unoriginal; based on another source",s:"The band's sound felt derivative of 90s rock."},
{w:"desiccate",p:"v",m:"to dry out thoroughly",s:"The desert sun quickly desiccated the fruit left outside."},
{w:"despot",p:"n",m:"a ruler with absolute power",s:"The despot silenced all opposition."},
{w:"deter",p:"v",m:"to discourage from acting",s:"Higher fines are meant to deter littering."},
{w:"diatribe",p:"n",m:"a forceful verbal attack",s:"He launched into a diatribe against his critics."},
{w:"dichotomy",p:"n",m:"a division into two opposites",s:"There's a clear dichotomy between theory and practice."},
{w:"didactic",p:"adj",m:"intended to teach or instruct",s:"The novel's ending felt overly didactic."},
{w:"diffident",p:"adj",m:"shy and lacking confidence",s:"The diffident student rarely spoke up in class."},
{w:"digress",p:"v",m:"to stray from the main topic",s:"The professor tends to digress into personal stories."},
{w:"dilapidated",p:"adj",m:"fallen into disrepair",s:"The dilapidated barn hadn't been used in years."},
{w:"diligent",p:"adj",m:"showing careful, persistent effort",s:"Her diligent research uncovered a key detail."},
{w:"diminutive",p:"adj",m:"very small",s:"A diminutive figure appeared at the end of the hall."},
{w:"disconcert",p:"v",m:"to unsettle or confuse",s:"The sudden question disconcerted the speaker."},
{w:"discordant",p:"adj",m:"lacking harmony; conflicting",s:"The committee's discordant opinions delayed the vote."},
{w:"discreet",p:"adj",m:"careful to avoid drawing attention",s:"He made a discreet exit before the argument began."},
{w:"discrepancy",p:"n",m:"a difference between things that should match",s:"An auditor found a discrepancy in the accounts."},
{w:"disdain",p:"n",m:"a feeling of contempt",s:"She viewed the plan with open disdain."},
{w:"disparage",p:"v",m:"to belittle or criticize",s:"He never disparages a competitor in public."},
{w:"disparate",p:"adj",m:"fundamentally different",s:"The report drew from disparate sources of data."},
{w:"dissemble",p:"v",m:"to conceal true feelings or motives",s:"He dissembled his anger with a polite smile."},
{w:"dissonance",p:"n",m:"a lack of harmony or agreement",s:"The chord's dissonance created tension in the piece."},
{w:"distend",p:"v",m:"to swell or expand",s:"The balloon distended until it nearly burst."},
{w:"docile",p:"adj",m:"easy to manage or teach",s:"The docile horse followed every command."},
{w:"dogmatic",p:"adj",m:"asserting opinions without room for debate",s:"His dogmatic views left no space for compromise."},
{w:"dormant",p:"adj",m:"inactive but capable of reactivation",s:"The volcano had lain dormant for centuries."},
{w:"dubious",p:"adj",m:"doubtful or questionable",s:"She gave a dubious excuse for being late."},
{w:"duplicity",p:"n",m:"deceitfulness",s:"His duplicity was exposed when the emails leaked."},
{w:"ebullient",p:"adj",m:"cheerful and full of energy",s:"The ebullient crowd cheered every goal."},
{w:"eccentric",p:"adj",m:"unconventional or slightly odd",s:"The eccentric professor wore mismatched socks daily."},
{w:"eclectic",p:"adj",m:"drawing from diverse sources",s:"Her music collection is wonderfully eclectic."},
{w:"edify",p:"v",m:"to instruct or improve morally",s:"The lecture was meant to edify, not entertain."},
{w:"efface",p:"v",m:"to erase or make inconspicuous",s:"Years of weather effaced the carving on the stone."},
{w:"effervescent",p:"adj",m:"lively and enthusiastic; bubbly",s:"Her effervescent personality lit up the room."},
{w:"effrontery",p:"n",m:"shameless boldness",s:"He had the effrontery to demand a raise after quitting."},
{w:"egalitarian",p:"adj",m:"believing in equality for all",s:"They built an egalitarian community with shared resources."},
{w:"egregious",p:"adj",m:"outstandingly bad; flagrant",s:"The report contained an egregious factual error."},
{w:"elicit",p:"v",m:"to draw out a response",s:"The ad was designed to elicit an emotional reaction."},
{w:"eloquent",p:"adj",m:"fluent and persuasive in speech",s:"Her eloquent speech moved the audience to tears."},
{w:"elusive",p:"adj",m:"difficult to find or catch",s:"A cure for the disease remained elusive."},
{w:"emaciated",p:"adj",m:"abnormally thin from starvation",s:"The rescued dog was emaciated and weak."},
{w:"embellish",p:"v",m:"to decorate or exaggerate",s:"He embellished the story to make it more exciting."},
{w:"empirical",p:"adj",m:"based on observation or experiment",s:"The theory needed empirical evidence to be accepted."},
{w:"emulate",p:"v",m:"to imitate in order to equal",s:"Young players try to emulate their favorite athletes."},
{w:"endemic",p:"adj",m:"native to or common in a region",s:"Malaria is endemic to parts of the tropics."},
{w:"enervate",p:"v",m:"to drain of energy",s:"The humid heat enervated the hikers by noon."},
{w:"engender",p:"v",m:"to give rise to",s:"The policy engendered widespread resentment."},
{w:"enigma",p:"n",m:"a puzzling mystery",s:"The disappearance remains an unsolved enigma.",f:"enigmatic (adj)"},
{w:"ephemeral",p:"adj",m:"lasting a very short time",s:"Fame in that industry is often ephemeral."},
{w:"equanimity",p:"n",m:"calmness under pressure",s:"She handled the crisis with remarkable equanimity."},
{w:"equivocal",p:"adj",m:"ambiguous or open to two interpretations",s:"His equivocal answer satisfied no one."},
{w:"erudite",p:"adj",m:"having great knowledge from study",s:"The erudite professor could quote any classic text."},
{w:"esoteric",p:"adj",m:"understood by only a small group",s:"The seminar covered esoteric details of tax law."},
{w:"eulogy",p:"n",m:"a speech of praise, often for the dead",s:"Her brother delivered a moving eulogy."},
{w:"euphemism",p:"n",m:"a mild word for something harsh",s:"'Passed away' is a common euphemism for died."},
{w:"evanescent",p:"adj",m:"quickly fading; fleeting",s:"The evanescent glow of fireflies lasted only seconds."},
{w:"exacerbate",p:"v",m:"to make a problem worse",s:"Cutting funding will only exacerbate the crisis."},
{w:"exalt",p:"v",m:"to praise highly; elevate",s:"The poem exalts the beauty of nature."},
{w:"exculpate",p:"v",m:"to clear of blame",s:"New DNA evidence exculpated the accused man."},
{w:"exemplary",p:"adj",m:"serving as a model; excellent",s:"Her exemplary conduct earned her a promotion."},
{w:"exigent",p:"adj",m:"urgent; pressing",s:"The team faced exigent demands before the deadline."},
{w:"exonerate",p:"v",m:"to clear of blame or fault",s:"The report exonerated the company of any wrongdoing."},
{w:"extol",p:"v",m:"to praise enthusiastically",s:"Critics extolled the film's stunning visuals."},
{w:"extraneous",p:"adj",m:"irrelevant or unnecessary",s:"Cut any extraneous details from your essay."},
{w:"exuberant",p:"adj",m:"full of energy and excitement",s:"The exuberant fans celebrated late into the night."},
{w:"fabricate",p:"v",m:"to invent falsely",s:"He fabricated an alibi to avoid suspicion."},
{w:"facetious",p:"adj",m:"joking, often inappropriately",s:"His facetious remark offended some of the guests."},
{w:"fallacious",p:"adj",m:"based on a mistaken belief",s:"The argument rested on a fallacious assumption."},
{w:"fastidious",p:"adj",m:"very attentive to detail; picky",s:"She is fastidious about keeping her desk organized."},
{w:"fatuous",p:"adj",m:"silly and pointless",s:"He made a fatuous comment that derailed the meeting."},
{w:"fervent",p:"adj",m:"having intense passion",s:"She is a fervent advocate for clean energy."},
{w:"flagrant",p:"adj",m:"obviously wrong and unashamed",s:"The referee called a flagrant foul."},
{w:"flippant",p:"adj",m:"disrespectfully casual",s:"His flippant tone annoyed the interviewer."},
{w:"florid",p:"adj",m:"excessively elaborate; flushed red",s:"The author's florid prose slowed the story down."},
{w:"foment",p:"v",m:"to stir up trouble",s:"The pamphlets were designed to foment rebellion."},
{w:"forbearance",p:"n",m:"patient self-control",s:"He showed great forbearance during the long delay."},
{w:"fortuitous",p:"adj",m:"happening by lucky chance",s:"Their meeting at the airport was entirely fortuitous."},
{w:"fractious",p:"adj",m:"irritable and hard to control",s:"The fractious committee couldn't agree on an agenda."},
{w:"frivolous",p:"adj",m:"not serious; trivial",s:"The judge dismissed the lawsuit as frivolous."},
{w:"frugal",p:"adj",m:"careful with money; thrifty",s:"Her frugal habits let her save half her income."},
{w:"furtive",p:"adj",m:"secretive and sly",s:"He gave a furtive glance toward the exit."},
{w:"garrulous",p:"adj",m:"excessively talkative",s:"The garrulous cab driver talked the entire ride."},
{w:"glib",p:"adj",m:"fluent but insincere",s:"His glib excuses no longer convinced anyone."},
{w:"grandiloquent",p:"adj",m:"pompous or extravagant in speech",s:"The CEO's grandiloquent promises rarely materialized."},
{w:"gratuitous",p:"adj",m:"uncalled for; unnecessary",s:"Critics called the film's violence gratuitous."},
{w:"gregarious",p:"adj",m:"sociable; enjoying company",s:"Her gregarious nature made her popular at parties."},
{w:"guile",p:"n",m:"cunning deception",s:"He won the negotiation through sheer guile."},
{w:"hackneyed",p:"adj",m:"overused and unoriginal",s:"The plot relied on a hackneyed twist ending."},
{w:"hapless",p:"adj",m:"unlucky",s:"The hapless intern spilled coffee on the CEO."},
{w:"haughty",p:"adj",m:"arrogantly proud",s:"Her haughty attitude alienated her coworkers."},
{w:"hedonist",p:"n",m:"one devoted to pleasure",s:"He lived as a hedonist, chasing comfort above all."},
{w:"heretical",p:"adj",m:"contrary to accepted belief",s:"His heretical theory challenged the entire field."},
{w:"hyperbole",p:"n",m:"exaggerated statement not meant literally",s:"Saying 'I've told you a million times' is hyperbole."},
{w:"iconoclast",p:"n",m:"one who attacks established beliefs",s:"The artist was an iconoclast who rejected tradition."},
{w:"idiosyncratic",p:"adj",m:"peculiar to an individual",s:"His idiosyncratic writing style is instantly recognizable."},
{w:"ignominious",p:"adj",m:"deserving public disgrace",s:"The team suffered an ignominious defeat at home."},
{w:"immutable",p:"adj",m:"unchanging over time",s:"The laws of physics are considered immutable."},
{w:"impassive",p:"adj",m:"showing no emotion",s:"The judge remained impassive as the verdict was read."},
{w:"impeccable",p:"adj",m:"flawless",s:"Her impeccable manners impressed everyone at dinner."},
{w:"impecunious",p:"adj",m:"having little or no money",s:"The impecunious student survived on instant noodles."},
{w:"imperious",p:"adj",m:"domineering; arrogantly commanding",s:"His imperious tone made the staff uneasy."},
{w:"impervious",p:"adj",m:"unable to be affected or penetrated",s:"He seemed impervious to criticism."},
{w:"implacable",p:"adj",m:"unable to be appeased",s:"She was an implacable opponent of the merger."},
{w:"implicit",p:"adj",m:"implied though not directly stated",s:"There was an implicit warning in his tone."},
{w:"impudent",p:"adj",m:"disrespectfully bold",s:"The impudent remark earned him a stern look."},
{w:"inadvertent",p:"adj",m:"unintentional",s:"The error was inadvertent, not deliberate."},
{w:"inane",p:"adj",m:"silly; lacking sense",s:"The meeting was full of inane small talk."},
{w:"inchoate",p:"adj",m:"just begun; not fully formed",s:"His plan was still inchoate and needed refining."},
{w:"incongruous",p:"adj",m:"out of place; inconsistent",s:"The skyscraper looked incongruous next to the old church."},
{w:"indefatigable",p:"adj",m:"tireless",s:"Her indefatigable energy kept the team going all night."},
{w:"indolent",p:"adj",m:"lazy",s:"The indolent cat slept through the entire afternoon."},
{w:"ineffable",p:"adj",m:"too great to be expressed in words",s:"She felt an ineffable joy watching the sunrise."},
{w:"inept",p:"adj",m:"lacking skill; incompetent",s:"His inept handling of the crisis cost him his job."},
{w:"inert",p:"adj",m:"lacking the ability to move or react",s:"Noble gases are chemically inert."},
{w:"inexorable",p:"adj",m:"impossible to stop or persuade",s:"The disease's inexorable spread alarmed officials."},
{w:"ingenuous",p:"adj",m:"innocent and unsuspecting",s:"His ingenuous questions revealed his inexperience."},
{w:"inimical",p:"adj",m:"harmful; hostile",s:"High interest rates are inimical to small businesses."},
{w:"iniquity",p:"n",m:"gross injustice or wickedness",s:"The novel exposes the iniquity of the prison system."},
{w:"innocuous",p:"adj",m:"harmless",s:"The comment seemed innocuous but caused an uproar."},
{w:"insipid",p:"adj",m:"lacking flavor or interest",s:"The soup was bland and insipid."},
{w:"insolent",p:"adj",m:"boldly disrespectful",s:"The insolent reply got him sent to the principal."},
{w:"insular",p:"adj",m:"narrow-minded; isolated",s:"Small towns can sometimes feel insular."},
{w:"intractable",p:"adj",m:"hard to control or solve",s:"Poverty remains an intractable problem worldwide."},
{w:"intransigent",p:"adj",m:"refusing to compromise",s:"The intransigent union rejected every offer."},
{w:"intrepid",p:"adj",m:"fearless and adventurous",s:"The intrepid explorer crossed the glacier alone."},
{w:"inundate",p:"v",m:"to overwhelm with a flood of things",s:"The office was inundated with complaints."},
{w:"inveterate",p:"adj",m:"habitual; long-established",s:"He is an inveterate gambler who can't quit."},
{w:"irascible",p:"adj",m:"easily angered",s:"The irascible chef yelled at anyone who was late."},
{w:"jubilant",p:"adj",m:"joyfully triumphant",s:"The jubilant fans stormed the field after the win."},
{w:"judicious",p:"adj",m:"having good judgment; wise",s:"A judicious use of resources saved the project."},
{w:"juxtapose",p:"v",m:"to place side by side for contrast",s:"The exhibit juxtaposes old photos with modern ones."},
{w:"laconic",p:"adj",m:"using very few words",s:"His laconic reply gave nothing away."},
{w:"lament",p:"v",m:"to express grief or sorrow",s:"She lamented the loss of the old neighborhood."},
{w:"languid",p:"adj",m:"lacking energy; slow-moving",s:"They spent a languid afternoon by the pool."},
{w:"largesse",p:"n",m:"generosity in giving",s:"The town thrived thanks to the founder's largesse."},
{w:"latent",p:"adj",m:"present but not yet developed",s:"The test revealed a latent talent for math."},
{w:"laud",p:"v",m:"to praise",s:"Reviewers lauded the film's daring cinematography."},
{w:"lethargic",p:"adj",m:"sluggish; lacking energy",s:"The heat made everyone feel lethargic."},
{w:"levity",p:"n",m:"lightheartedness; humor",s:"He added a bit of levity to ease the tension."},
{w:"loquacious",p:"adj",m:"very talkative",s:"The loquacious tour guide never paused for breath."},
{w:"lucid",p:"adj",m:"clear and easy to understand",s:"She gave a lucid explanation of the theorem."},
{w:"lucrative",p:"adj",m:"profitable",s:"He left teaching for a more lucrative career."},
{w:"magnanimous",p:"adj",m:"generous, especially toward a rival",s:"The champion was magnanimous in victory."},
{w:"malaise",p:"n",m:"a general feeling of unease",s:"A sense of malaise settled over the struggling company."},
{w:"malinger",p:"v",m:"to fake illness to avoid work",s:"He was accused of malingering to skip his shift."},
{w:"malleable",p:"adj",m:"easily shaped or influenced",s:"Gold is a highly malleable metal."},
{w:"maverick",p:"n",m:"an independent-minded person",s:"The maverick engineer ignored standard procedure."},
{w:"mendacious",p:"adj",m:"lying; untruthful",s:"The witness gave a mendacious account of events."},
{w:"mercurial",p:"adj",m:"unpredictable; changing moods quickly",s:"Her mercurial temper made her hard to work with."},
{w:"meticulous",p:"adj",m:"extremely careful and precise",s:"His meticulous planning left nothing to chance."},
{w:"misanthrope",p:"n",m:"one who dislikes humankind",s:"The old hermit was known as the town's misanthrope."},
{w:"mitigate",p:"v",m:"to make less severe",s:"Seatbelts help mitigate injuries in crashes."},
{w:"mollify",p:"v",m:"to calm or soothe anger",s:"The manager tried to mollify the angry customer."},
{w:"morose",p:"adj",m:"sullen and gloomy",s:"He's been morose since losing his job."},
{w:"mundane",p:"adj",m:"ordinary; lacking excitement",s:"She was tired of the mundane office routine."},
{w:"myriad",p:"adj",m:"a great many",s:"The city offers myriad dining options."},
{w:"nadir",p:"n",m:"the lowest point",s:"The recession marked the nadir of the company's history."},
{w:"nefarious",p:"adj",m:"wicked; villainous",s:"The film's nefarious villain plots to steal the crown."},
{w:"neophyte",p:"n",m:"a beginner",s:"As a neophyte, she asked many basic questions."},
{w:"nonchalant",p:"adj",m:"calm and casually unconcerned",s:"He stayed nonchalant despite the chaos around him."},
{w:"nostalgia",p:"n",m:"sentimental longing for the past",s:"The old song filled her with nostalgia."},
{w:"novice",p:"n",m:"a beginner",s:"The novice climber stuck to easier trails."},
{w:"obdurate",p:"adj",m:"stubbornly refusing to change",s:"He remained obdurate despite everyone's objections."},
{w:"obfuscate",p:"v",m:"to make unclear or confusing",s:"The report seemed designed to obfuscate the real costs."},
{w:"obsequious",p:"adj",m:"excessively eager to please",s:"The obsequious waiter hovered over every table."},
{w:"obstinate",p:"adj",m:"stubbornly refusing to change one's mind",s:"The obstinate toddler refused to put on shoes."},
{w:"obtuse",p:"adj",m:"slow to understand; dull",s:"His obtuse response showed he'd missed the point."},
{w:"officious",p:"adj",m:"excessively eager to give orders",s:"The officious clerk demanded forms no one had heard of."},
{w:"onerous",p:"adj",m:"burdensome",s:"The new regulations placed an onerous burden on small firms."},
{w:"opaque",p:"adj",m:"not transparent; hard to understand",s:"The company's finances were deliberately opaque."},
{w:"opulent",p:"adj",m:"luxurious; wealthy",s:"The hotel lobby was opulent, with marble everywhere."},
{w:"ostentatious",p:"adj",m:"showy; designed to impress",s:"His ostentatious mansion had gold-plated fixtures."},
{w:"ostracize",p:"v",m:"to exclude from a group",s:"He was ostracized by his classmates after the incident."},
{w:"panacea",p:"n",m:"a solution for all problems",s:"There is no single panacea for climate change."},
{w:"paradigm",p:"n",m:"a typical example or model",s:"The discovery created a new scientific paradigm."},
{w:"paragon",p:"n",m:"a model of excellence",s:"She is a paragon of professionalism."},
{w:"paramount",p:"adj",m:"more important than anything else",s:"Safety is paramount during the construction project."},
{w:"parochial",p:"adj",m:"narrow in scope or outlook",s:"His parochial view ignored global trends."},
{w:"parsimonious",p:"adj",m:"extremely unwilling to spend money",s:"The parsimonious landlord refused to fix anything."},
{w:"partisan",p:"adj",m:"strongly biased toward one side",s:"The debate quickly became partisan and heated."},
{w:"pathos",p:"n",m:"a quality that evokes pity or sadness",s:"The film's ending is full of pathos."},
{w:"paucity",p:"n",m:"a scarcity or small amount",s:"There is a paucity of evidence for the claim."},
{w:"pedantic",p:"adj",m:"overly concerned with minor details or rules",s:"His pedantic corrections annoyed the whole class."},
{w:"pellucid",p:"adj",m:"transparently clear",s:"The lake's pellucid water revealed every stone below."},
{w:"penchant",p:"n",m:"a strong liking for something",s:"She has a penchant for spicy food."},
{w:"penury",p:"n",m:"extreme poverty",s:"The family lived in penury after the factory closed."},
{w:"perfunctory",p:"adj",m:"done with minimal effort or care",s:"He gave a perfunctory nod and walked away."},
{w:"pernicious",p:"adj",m:"harmful in a gradual way",s:"Misinformation has a pernicious effect on public trust."},
{w:"perspicacious",p:"adj",m:"having keen insight",s:"The perspicacious detective noticed the tiny clue."},
{w:"pertinent",p:"adj",m:"relevant to the matter at hand",s:"She asked several pertinent questions after the talk."},
{w:"pervasive",p:"adj",m:"spreading widely throughout",s:"Smartphones have become pervasive in daily life."},
{w:"phlegmatic",p:"adj",m:"calm and unemotional",s:"He stayed phlegmatic even during the emergency."},
{w:"placate",p:"v",m:"to calm or appease",s:"The airline offered vouchers to placate angry passengers."},
{w:"placid",p:"adj",m:"calm and peaceful",s:"The lake was placid at sunrise."},
{w:"platitude",p:"n",m:"a trite, overused remark",s:"His speech was full of empty platitudes."},
{w:"plausible",p:"adj",m:"seeming reasonable or probable",s:"She offered a plausible explanation for the delay."},
{w:"plethora",p:"n",m:"an excessive amount",s:"The menu offers a plethora of vegetarian options."},
{w:"poignant",p:"adj",m:"deeply moving; touching",s:"The memoir includes a poignant chapter on loss."},
{w:"polemical",p:"adj",m:"controversial; argumentative",s:"His polemical essay sparked heated debate."},
{w:"pragmatic",p:"adj",m:"practical rather than idealistic",s:"She took a pragmatic approach to solving the budget crisis."},
{w:"precarious",p:"adj",m:"unstable; likely to fail",s:"The ladder was in a precarious position."},
{w:"precocious",p:"adj",m:"showing advanced development early",s:"The precocious child was reading novels at age six."},
{w:"predilection",p:"n",m:"a preference for something",s:"He has a predilection for old jazz records."},
{w:"prevaricate",p:"v",m:"to speak evasively; lie",s:"The witness prevaricated instead of answering directly."},
{w:"pristine",p:"adj",m:"clean and unspoiled",s:"The beach remained pristine, untouched by tourists."},
{w:"probity",p:"n",m:"honesty and integrity",s:"The judge was known for her unwavering probity."},
{w:"prodigal",p:"adj",m:"wastefully extravagant",s:"The prodigal heir spent his fortune within a year."},
{w:"prodigious",p:"adj",m:"remarkably great in size or ability",s:"She showed a prodigious talent for chess."},
{w:"profligate",p:"adj",m:"recklessly wasteful",s:"Profligate spending left the city deeply in debt."},
{w:"profound",p:"adj",m:"very great; deeply insightful",s:"The book had a profound effect on her worldview."},
{w:"proliferate",p:"v",m:"to increase rapidly in number",s:"Startups proliferated during the tech boom."},
{w:"prosaic",p:"adj",m:"dull; lacking imagination",s:"His prosaic writing style put readers to sleep."},
{w:"protean",p:"adj",m:"readily changing shape or form",s:"The actor is known for his protean range of roles."},
{w:"provincial",p:"adj",m:"narrow or unsophisticated; rural",s:"His provincial upbringing shaped his simple tastes."},
{w:"prudent",p:"adj",m:"showing careful judgment",s:"It's prudent to save part of every paycheck."},
{w:"pugnacious",p:"adj",m:"eager to fight or argue",s:"The pugnacious boxer taunted his opponent before the match."},
{w:"pundit",p:"n",m:"an expert who gives opinions publicly",s:"Political pundits debated the election results all night."},
{w:"quaint",p:"adj",m:"charmingly old-fashioned",s:"The village had quaint cobblestone streets."},
{w:"querulous",p:"adj",m:"complaining in a whiny way",s:"The querulous passenger complained about every delay."},
{w:"quiescent",p:"adj",m:"in a state of rest; inactive",s:"The volcano remained quiescent for decades."},
{w:"quixotic",p:"adj",m:"unrealistically idealistic",s:"His quixotic plan to end poverty overnight was doomed."},
{w:"rancor",p:"n",m:"deep bitterness or resentment",s:"Years later, the rancor between them still lingered."},
{w:"recalcitrant",p:"adj",m:"stubbornly resistant to authority",s:"The recalcitrant student refused to follow any rules."},
{w:"reclusive",p:"adj",m:"avoiding the company of others",s:"The reclusive author never gave interviews."},
{w:"redundant",p:"adj",m:"unnecessarily repetitive",s:"The report was full of redundant phrases."},
{w:"refute",p:"v",m:"to prove wrong",s:"New evidence refuted the earlier theory."},
{w:"relegate",p:"v",m:"to assign to a lower position",s:"The team was relegated to the second division."},
{w:"remedial",p:"adj",m:"intended to correct a problem",s:"She took remedial classes to catch up in math."},
{w:"renounce",p:"v",m:"to formally give up",s:"He renounced his claim to the throne."},
{w:"reprehensible",p:"adj",m:"deserving strong condemnation",s:"The coach's behavior was widely called reprehensible."},
{w:"reprove",p:"v",m:"to gently criticize or scold",s:"She reproved him for arriving late again."},
{w:"repudiate",p:"v",m:"to reject or disown",s:"He publicly repudiated his earlier statements."},
{w:"rescind",p:"v",m:"to cancel or revoke",s:"The company rescinded the job offer after the background check."},
{w:"reticent",p:"adj",m:"reserved; reluctant to speak",s:"She was reticent about discussing her past."},
{w:"reverent",p:"adj",m:"showing deep respect",s:"The crowd fell into a reverent silence."},
{w:"rhetoric",p:"n",m:"persuasive speech or writing",s:"His campaign relied heavily on emotional rhetoric."},
{w:"sagacious",p:"adj",m:"showing wisdom and sound judgment",s:"The sagacious elder offered valuable advice."},
{w:"salient",p:"adj",m:"most noticeable or important",s:"Let's focus on the salient points of the proposal."},
{w:"sanguine",p:"adj",m:"optimistic; confident",s:"She remained sanguine despite the setbacks."},
{w:"sardonic",p:"adj",m:"mocking; cynically humorous",s:"He gave a sardonic smile at the absurd rule."},
{w:"satiate",p:"v",m:"to satisfy fully",s:"The huge meal satiated even the hungriest guest."},
{w:"scrupulous",p:"adj",m:"extremely thorough and careful",s:"She kept scrupulous records of every transaction."},
{w:"sedulous",p:"adj",m:"diligent and persistent",s:"His sedulous efforts finally paid off."},
{w:"serendipity",p:"n",m:"a fortunate accidental discovery",s:"Finding the old photo was pure serendipity."},
{w:"servile",p:"adj",m:"excessively submissive",s:"His servile attitude toward the boss annoyed coworkers."},
{w:"skeptic",p:"n",m:"one who doubts accepted beliefs",s:"She remained a skeptic about the miracle cure."},
{w:"solicitous",p:"adj",m:"showing great concern for someone",s:"The nurse was solicitous about her patient's comfort."},
{w:"solvent",p:"adj",m:"able to pay one's debts",s:"The company stayed solvent despite the recession."},
{w:"soporific",p:"adj",m:"causing sleepiness",s:"The lecture's monotone voice was soporific."},
{w:"sparse",p:"adj",m:"thinly spread; scanty",s:"The desert had only sparse vegetation."},
{w:"spurious",p:"adj",m:"false, though appearing genuine",s:"The claim turned out to be spurious."},
{w:"staid",p:"adj",m:"sedate and unadventurous",s:"The staid old bank resisted any modern changes."},
{w:"stoic",p:"adj",m:"enduring hardship without complaint",s:"He remained stoic throughout the painful recovery."},
{w:"stolid",p:"adj",m:"showing little emotion",s:"The stolid guard didn't react to the commotion."},
{w:"stringent",p:"adj",m:"strict; rigorously enforced",s:"The lab follows stringent safety protocols."},
{w:"subtle",p:"adj",m:"delicate; not obvious",s:"There was a subtle change in her tone."},
{w:"superfluous",p:"adj",m:"more than necessary",s:"He cut every superfluous word from the draft."},
{w:"sycophant",p:"n",m:"one who flatters for self-interest",s:"The king was surrounded by sycophants."},
{w:"taciturn",p:"adj",m:"reserved; saying little",s:"The taciturn farmer answered in single words."},
{w:"tangential",p:"adj",m:"only slightly related to the main topic",s:"His comment was tangential to the discussion."},
{w:"temperate",p:"adj",m:"moderate; not extreme",s:"The region has a mild, temperate climate."},
{w:"tenacious",p:"adj",m:"persistent and determined",s:"Her tenacious spirit helped her finish the marathon."},
{w:"tenuous",p:"adj",m:"weak; barely holding together",s:"The evidence for his theory was tenuous at best."},
{w:"terse",p:"adj",m:"brief and to the point",s:"He gave a terse reply and hung up."},
{w:"torpid",p:"adj",m:"sluggish; lacking energy",s:"The bear stayed torpid through the winter months."},
{w:"tractable",p:"adj",m:"easy to control or manage",s:"The new hire proved tractable and eager to learn."},
{w:"tranquil",p:"adj",m:"calm and peaceful",s:"The garden was a tranquil escape from the city."},
{w:"transient",p:"adj",m:"lasting only a short time",s:"The town sees many transient visitors each summer."},
{w:"trepidation",p:"n",m:"fear or anxiety about something",s:"She approached the interview with trepidation."},
{w:"trite",p:"adj",m:"overused and unoriginal",s:"The ending felt trite and predictable."},
{w:"trivial",p:"adj",m:"of little importance",s:"They argued over a trivial detail for an hour."},
{w:"truculent",p:"adj",m:"eager to argue or fight",s:"The truculent teenager snapped at every question."},
{w:"ubiquitous",p:"adj",m:"present everywhere",s:"Smartphones are now ubiquitous in modern life."},
{w:"unctuous",p:"adj",m:"excessively flattering; oily",s:"The unctuous salesman made her uncomfortable."},
{w:"undermine",p:"v",m:"to weaken gradually",s:"Constant criticism undermined his confidence."},
{w:"urbane",p:"adj",m:"sophisticated and refined",s:"His urbane manner impressed the diplomats."},
{w:"vacillate",p:"v",m:"to waver between choices",s:"She vacillated for hours before choosing a college."},
{w:"venerate",p:"v",m:"to regard with great respect",s:"The community venerates the founding elders."},
{w:"veracity",p:"n",m:"truthfulness; accuracy",s:"Journalists questioned the veracity of the report."},
{w:"verbose",p:"adj",m:"using more words than necessary",s:"His verbose emails often lost the reader's attention."},
{w:"vestige",p:"n",m:"a remaining trace of something",s:"The ruins are a vestige of the ancient city."},
{w:"vex",p:"v",m:"to annoy or frustrate",s:"The constant delays vexed the commuters."},
{w:"vindicate",p:"v",m:"to clear of blame; justify",s:"The test results vindicated her original theory."},
{w:"vindictive",p:"adj",m:"seeking revenge",s:"His vindictive comments revealed lingering resentment."},
{w:"virtuoso",p:"n",m:"a person with masterly skill",s:"The violinist is a true virtuoso."},
{w:"viscous",p:"adj",m:"thick and slow-flowing",s:"The viscous syrup barely moved off the spoon."},
{w:"vitriolic",p:"adj",m:"filled with bitter criticism",s:"His vitriolic review devastated the young author."},
{w:"vociferous",p:"adj",m:"loud and forceful in expression",s:"The vociferous crowd demanded a refund."},
{w:"volatile",p:"adj",m:"unpredictable; likely to change suddenly",s:"The stock market has been extremely volatile this year."},
{w:"wary",p:"adj",m:"cautious of possible danger",s:"She was wary of strangers offering deals."},
{w:"whimsical",p:"adj",m:"playfully quirky",s:"The children's book had a whimsical illustration style."},
{w:"zealous",p:"adj",m:"showing great enthusiasm for a cause",s:"He was a zealous supporter of the recycling program."},
{w:"zenith",p:"n",m:"the highest point",s:"The empire reached its zenith in the 2nd century."},
{w:"abandon",p:"v",m:"to give up completely",s:"The captain refused to abandon the sinking ship."},
{w:"abrasive",p:"adj",m:"harsh in manner",s:"His abrasive tone alienated several colleagues."},
{w:"abreast",p:"adv",m:"side by side; up to date with",s:"She reads journals to stay abreast of new research."},
{w:"abridge",p:"v",m:"to shorten a piece of writing",s:"The editor abridged the novel for younger readers."},
{w:"accentuate",p:"v",m:"to emphasize or highlight",s:"The dim lighting accentuated the shadows in the room."},
{w:"accord",p:"n",m:"agreement; harmony",s:"The two nations reached an accord after months of talks."},
{w:"acquisitive",p:"adj",m:"eager to acquire possessions",s:"His acquisitive nature filled the house with unused gadgets."},
{w:"activism",p:"n",m:"vigorous campaigning for social change",s:"Her activism helped pass the new clean-air law."},
{w:"acute",p:"adj",m:"sharp or intense; keenly perceptive",s:"He has an acute sense of when something is wrong."},
{w:"affectation",p:"n",m:"an unnatural manner adopted to impress",s:"His British accent was just an affectation."},
{w:"aghast",p:"adj",m:"filled with horror or shock",s:"She was aghast at the size of the repair bill."},
{w:"alienate",p:"v",m:"to make someone feel isolated",s:"His harsh criticism alienated his closest friends."},
{w:"aloof",p:"adj",m:"distant and uninvolved",s:"The new manager seemed aloof during his first week."},
{w:"ambiguity",p:"n",m:"the quality of having more than one meaning",s:"The contract's ambiguity led to a lawsuit."},
{w:"antagonistic",p:"adj",m:"showing hostility",s:"The two rivals remained antagonistic for years."},
{w:"antedate",p:"v",m:"to precede in time",s:"This manuscript antedates the printing press by centuries."},
{w:"amuse",p:"v",m:"to entertain or cause to laugh",s:"The clown's antics amused the children for hours."},
{w:"antiquity",p:"n",m:"the ancient past",s:"The museum houses artifacts from antiquity."},
{w:"antithesis",p:"n",m:"the direct opposite",s:"Cruelty is the antithesis of kindness."},
{w:"aplomb",p:"n",m:"self-confidence and composure",s:"She handled the tough questions with aplomb."},
{w:"apologist",p:"n",m:"one who defends a controversial cause",s:"He became an apologist for the failed policy."},
{w:"apt",p:"adj",m:"fitting or appropriate; likely",s:"That was an apt description of the chaos in the office."},
{w:"appropriate",p:"v",m:"to take for one's own use without permission",s:"The committee appropriated funds meant for repairs."},
{w:"assertive",p:"adj",m:"confident and direct in stating one's views",s:"Being assertive helped her negotiate a better salary."},
{w:"astonish",p:"v",m:"to surprise greatly",s:"The magician's final trick astonished the crowd."},
{w:"astounded",p:"adj",m:"greatly surprised or shocked",s:"We were astounded by how quickly the project finished."},
{w:"attainment",p:"n",m:"the act of achieving something",s:"Her attainment of the degree took six years."},
{w:"attribute",p:"v",m:"to regard as caused by",s:"Historians attribute the empire's fall to overexpansion."},
{w:"augment",p:"v",m:"to make greater in size or value",s:"The company augmented its staff before the holidays."},
{w:"austerity",p:"n",m:"severe simplicity; strict economic measures",s:"The government introduced austerity to cut the deficit."},
{w:"avert",p:"v",m:"to prevent or turn away",s:"Quick thinking averted a serious accident."},
{w:"banish",p:"v",m:"to send away as punishment",s:"The king banished the traitor from the kingdom."},
{w:"bearing",p:"n",m:"a person's manner or posture; relevance",s:"His confident bearing put the jury at ease."},
{w:"befriend",p:"v",m:"to become a friend to",s:"She befriended the new student on his first day."},
{w:"beguile",p:"v",m:"to charm, often deceptively",s:"The salesman beguiled customers with false promises."},
{w:"beholden",p:"adj",m:"owing something to another",s:"He felt beholden to the mentor who trained him."},
{w:"bemuse",p:"v",m:"to confuse or puzzle",s:"The strange instructions bemused the entire class."},
{w:"betray",p:"v",m:"to be disloyal to; reveal unintentionally",s:"His trembling hands betrayed his nervousness."},
{w:"bias",p:"n",m:"a tendency to favor one side",s:"The study was criticized for its bias."},
{w:"blemish",p:"n",m:"a flaw that spoils appearance",s:"A single blemish ruined the otherwise perfect fruit."},
{w:"blight",p:"n",m:"a thing that damages or destroys",s:"Pollution is a blight on the city's rivers."},
{w:"blithe",p:"adj",m:"carefree and cheerful, often without concern",s:"Her blithe attitude toward deadlines worried her boss."},
{w:"blunt",p:"adj",m:"direct and plainspoken; not sharp",s:"He gave a blunt assessment of the team's performance."},
{w:"bogus",p:"adj",m:"not genuine; fake",s:"They were arrested for selling bogus concert tickets."},
{w:"boon",p:"n",m:"a helpful benefit",s:"The new highway was a boon for local businesses."},
{w:"braggart",p:"n",m:"a person who boasts",s:"No one believed the braggart's wild stories."},
{w:"brandish",p:"v",m:"to wave something menacingly",s:"The actor brandished a prop sword on stage."},
{w:"brazen",p:"adj",m:"bold and shameless",s:"It was a brazen attempt to cheat on the exam."},
{w:"bridle",p:"v",m:"to restrain or hold back",s:"She bridled her anger during the meeting."},
{w:"bucolic",p:"adj",m:"relating to pleasant rural life",s:"They retired to a bucolic village in the countryside."},
{w:"buoyancy",p:"n",m:"the ability to float; cheerfulness",s:"Her natural buoyancy lifted the team's spirits."},
{w:"calamitous",p:"adj",m:"disastrous",s:"The flood had calamitous effects on the region."},
{w:"callous",p:"adj",m:"insensitive to others' feelings",s:"His callous remarks hurt the grieving family."},
{w:"calumny",p:"n",m:"false statements damaging a reputation",s:"The politician was the target of vicious calumny."},
{w:"canny",p:"adj",m:"shrewd and careful, especially with money",s:"The canny investor avoided the risky stock."},
{w:"canonize",p:"v",m:"to officially recognize as important",s:"The film has since been canonized as a classic."},
{w:"caprice",p:"n",m:"a sudden, unpredictable change of mood",s:"The ruler governed by caprice rather than law."},
{w:"catastrophe",p:"n",m:"a sudden disaster",s:"The flood was an economic catastrophe for the region."},
{w:"cerebral",p:"adj",m:"intellectual rather than emotional",s:"The film was praised for its cerebral plot."},
{w:"check",p:"v",m:"to stop or restrain",s:"New regulations helped check the spread of the disease."},
{w:"cherish",p:"v",m:"to protect and care for lovingly",s:"She cherished the letters her grandmother wrote."},
{w:"circumscribe",p:"v",m:"to restrict within limits",s:"His authority was circumscribed by the new constitution."},
{w:"circumstantial",p:"adj",m:"based on inference, not direct proof",s:"The verdict relied heavily on circumstantial evidence."},
{w:"clanger",p:"n",m:"an embarrassing mistake",s:"He dropped a real clanger during the toast."},
{w:"clear-headed",p:"adj",m:"able to think clearly and sensibly",s:"A clear-headed pilot guided the plane safely down."},
{w:"clerical",p:"adj",m:"relating to office work or the clergy",s:"The error was simply a clerical mistake."},
{w:"cloak",p:"v",m:"to cover or conceal",s:"Fog cloaked the harbor that morning."},
{w:"clumsy",p:"adj",m:"awkward in movement or handling",s:"His clumsy attempt to fix the sink flooded the kitchen."},
{w:"collude",p:"v",m:"to cooperate secretly for a deceitful purpose",s:"The two firms colluded to fix prices."},
{w:"commonplace",p:"adj",m:"ordinary; not unusual",s:"Video calls have become commonplace at work."},
{w:"compel",p:"v",m:"to force someone to do something",s:"Financial pressure compelled her to sell the house."},
{w:"complementary",p:"adj",m:"completing or enhancing something else",s:"The two flavors are complementary, not competing."},
{w:"compliance",p:"n",m:"the act of obeying rules or requests",s:"The factory is now in full compliance with safety codes."},
{w:"conditional",p:"adj",m:"dependent on certain conditions",s:"The offer was conditional on passing a background check."},
{w:"confound",p:"v",m:"to confuse or baffle",s:"The results confounded even the lead researcher."},
{w:"consensus",p:"n",m:"general agreement",s:"The board reached consensus after a long debate."},
{w:"contemporary",p:"adj",m:"belonging to the present time",s:"The museum focuses on contemporary art."},
{w:"contemptuous",p:"adj",m:"showing scorn or disdain",s:"He gave a contemptuous laugh at the suggestion."},
{w:"contend",p:"v",m:"to struggle or compete; to assert",s:"Lawyers contend that the law is unconstitutional."},
{w:"contentment",p:"n",m:"a state of happy satisfaction",s:"She found contentment in her quiet garden."},
{w:"cope",p:"v",m:"to deal effectively with something difficult",s:"He struggled to cope with the sudden change."},
{w:"copious",p:"adj",m:"abundant in quantity",s:"She took copious notes during the lecture."},
{w:"counterfeit",p:"adj",m:"made in imitation to deceive",s:"Police seized thousands of counterfeit bills."},
{w:"counterintuitive",p:"adj",m:"contrary to what one would expect",s:"It's counterintuitive, but slower running can build more endurance."},
{w:"counterproductive",p:"adj",m:"having the opposite of the intended effect",s:"Yelling at tired employees is often counterproductive."},
{w:"cow",p:"v",m:"to intimidate into submission",s:"The bully tried to cow the younger students."},
{w:"crafty",p:"adj",m:"cleverly deceitful",s:"The crafty fox slipped past the guard dogs."},
{w:"crestfallen",p:"adj",m:"sad and disappointed",s:"The team looked crestfallen after the final loss."},
{w:"cunning",p:"adj",m:"skillfully deceptive",s:"The cunning thief avoided every camera."},
{w:"curtail",p:"v",m:"to reduce or cut short",s:"The airline curtailed flights during the storm."},
{w:"daunt",p:"v",m:"to intimidate or discourage",s:"The steep climb didn't daunt the experienced hikers."},
{w:"debunk",p:"v",m:"to expose the falseness of a claim",s:"Scientists debunked the myth within days."},
{w:"deceit",p:"n",m:"dishonest behavior meant to mislead",s:"Their entire scheme was built on deceit."},
{w:"deceptive",p:"adj",m:"misleading",s:"The ad's deceptive claims led to a lawsuit."},
{w:"defamatory",p:"adj",m:"damaging to someone's reputation",s:"The magazine printed a defamatory story about the actor."},
{w:"deferential",p:"adj",m:"showing respect for another's wishes",s:"He was deferential toward his elders."},
{w:"deft",p:"adj",m:"skillful and quick in movement",s:"Her deft fingers repaired the watch in minutes."},
{w:"defy",p:"v",m:"to openly resist or refuse to obey",s:"The workers defied the order to return early."},
{w:"demur",p:"v",m:"to raise objections; hesitate",s:"She demurred when asked to sign the waiver."},
{w:"denigrate",p:"v",m:"to criticize unfairly; belittle",s:"He denigrated his rival's work in the review."},
{w:"detrimental",p:"adj",m:"harmful",s:"Skipping sleep is detrimental to memory."},
{w:"devious",p:"adj",m:"showing skill in deceiving",s:"He used a devious scheme to dodge the fee."},
{w:"devolve",p:"v",m:"to pass down or transfer, often downward",s:"Power slowly devolved from the crown to parliament."},
{w:"diffuse",p:"adj",m:"spread out over a wide area",s:"The gas diffused quickly through the room."},
{w:"disaffection",p:"n",m:"dissatisfaction leading to disloyalty",s:"Growing disaffection led to the strike."},
{w:"disapprobation",p:"n",m:"strong disapproval",s:"The critic's review expressed clear disapprobation."},
{w:"discern",p:"v",m:"to perceive or recognize clearly",s:"It was hard to discern his true intentions."},
{w:"discomfort",p:"n",m:"a feeling of unease",s:"The tight shoes caused mild discomfort."},
{w:"discount",p:"v",m:"to dismiss as unimportant",s:"Investors discounted the rumor entirely."},
{w:"discredit",p:"v",m:"to damage the reputation of",s:"The scandal discredited the entire campaign."},
{w:"disentangle",p:"v",m:"to free from a tangled state",s:"It took hours to disentangle the fishing lines."},
{w:"disgruntled",p:"adj",m:"annoyed and dissatisfied",s:"A disgruntled customer left a harsh review."},
{w:"disintegrate",p:"v",m:"to break apart into fragments",s:"The old bridge began to disintegrate."},
{w:"disinterested",p:"adj",m:"unbiased; not influenced by personal interest",s:"A disinterested judge was chosen for the case."},
{w:"dislocate",p:"v",m:"to displace from the normal position",s:"He dislocated his shoulder during the match."},
{w:"dismantle",p:"v",m:"to take apart piece by piece",s:"Workers dismantled the old factory over months."},
{w:"dispassionate",p:"adj",m:"not influenced by emotion",s:"She gave a dispassionate account of the accident."},
{w:"dispense",p:"v",m:"to distribute; to do without",s:"The clinic dispenses free vaccines every Friday."},
{w:"disquiet",p:"n",m:"a feeling of anxiety",s:"News of the layoffs caused deep disquiet."},
{w:"disseminate",p:"v",m:"to spread widely",s:"The agency disseminates weather warnings by text."},
{w:"dissimilar",p:"adj",m:"not alike",s:"The two proposals were completely dissimilar."},
{w:"dissolution",p:"n",m:"the act of ending or breaking up",s:"The dissolution of the partnership took months."},
{w:"distill",p:"v",m:"to extract the essential meaning; purify",s:"The report distills years of research into ten pages."},
{w:"distort",p:"v",m:"to twist out of a true or natural shape",s:"The lens distorted the image at the edges."},
{w:"divergent",p:"adj",m:"developing in different directions",s:"The two theories are wildly divergent."},
{w:"doctrinaire",p:"adj",m:"rigidly adhering to theory over practice",s:"His doctrinaire approach ignored real-world constraints."},
{w:"dynamism",p:"n",m:"energy and vigorous activity",s:"The city's dynamism attracts young entrepreneurs."},
{w:"eclipse",p:"v",m:"to surpass in significance",s:"Her later work eclipsed her early novels."},
{w:"ecstatic",p:"adj",m:"feeling intense joy",s:"She was ecstatic after hearing the news."},
{w:"efficacy",p:"n",m:"the ability to produce a desired result",s:"Trials confirmed the vaccine's efficacy."},
{w:"egoism",p:"n",m:"excessive focus on oneself",s:"His egoism made teamwork difficult."},
{w:"egotist",p:"n",m:"a self-centered person",s:"The egotist rarely asked about others' lives."},
{w:"elated",p:"adj",m:"extremely happy",s:"The team was elated after the championship win."},
{w:"elevate",p:"v",m:"to raise to a higher position",s:"The promotion elevated her to department head."},
{w:"eloquence",p:"n",m:"fluent, persuasive speaking ability",s:"His eloquence won over the skeptical crowd."},
{w:"empathy",p:"n",m:"the ability to understand others' feelings",s:"Good doctors show empathy toward frightened patients."},
{w:"enchant",p:"v",m:"to fill with delight; bewitch",s:"The melody enchanted the entire audience."},
{w:"endanger",p:"v",m:"to put at risk of harm",s:"Overfishing endangers the coral reef ecosystem."},
{w:"endorse",p:"v",m:"to publicly declare support for",s:"The senator endorsed the new bill."},
{w:"enfeeble",p:"v",m:"to make weak",s:"Years of drought enfeebled the once-thriving farm."},
{w:"engage",p:"v",m:"to occupy attention; to participate",s:"The lecture failed to engage the tired students."},
{w:"enigmatic",p:"adj",m:"mysterious and difficult to understand",s:"The artist's enigmatic smile puzzled viewers for centuries."},
{w:"entail",p:"v",m:"to involve as a necessary consequence",s:"The job entails frequent overseas travel."},
{w:"entreat",p:"v",m:"to ask earnestly",s:"She entreated the judge for leniency."},
{w:"entrenched",p:"adj",m:"firmly established, hard to change",s:"Corruption was deeply entrenched in the agency."},
{w:"equitable",p:"adj",m:"fair and impartial",s:"The judge sought an equitable division of assets."},
{w:"erode",p:"v",m:"to gradually wear away",s:"The cliffs have eroded significantly over decades."},
{w:"erratic",p:"adj",m:"inconsistent; unpredictable",s:"His erratic driving alarmed the other passengers."},
{w:"erroneous",p:"adj",m:"incorrect",s:"The report contained several erroneous statistics."},
{w:"erstwhile",p:"adj",m:"former",s:"Her erstwhile business partner now works for a rival."},
{w:"estranged",p:"adj",m:"no longer close or in contact",s:"He reconciled with his estranged brother."},
{w:"euphoric",p:"adj",m:"feeling intense excitement or happiness",s:"The crowd was euphoric after the last-minute goal."},
{w:"evasive",p:"adj",m:"avoiding direct answers",s:"His evasive answers frustrated the reporters."},
{w:"exacting",p:"adj",m:"demanding great care and effort",s:"The exacting professor accepted no late work."},
{w:"exigence",p:"n",m:"an urgent need or demand",s:"The exigence of the crisis forced quick action."},
{w:"exotic",p:"adj",m:"unusual and foreign in appeal",s:"They served exotic fruits from Southeast Asia."},
{w:"expedient",p:"adj",m:"convenient though possibly improper",s:"He chose the expedient solution over the ethical one."},
{w:"explicit",p:"adj",m:"clearly stated, leaving no doubt",s:"The instructions were explicit about safety gear."},
{w:"exploit",p:"v",m:"to use selfishly for one's own benefit",s:"The factory was accused of exploiting its workers."},
{w:"exposition",p:"n",m:"a comprehensive explanation",s:"The essay opens with a long exposition of the theory."},
{w:"extant",p:"adj",m:"still in existence",s:"Only a few extant copies of the manuscript remain."},
{w:"extravagance",p:"n",m:"excessive spending or lack of restraint",s:"The wedding was criticized for its extravagance."},
{w:"factual",p:"adj",m:"based on facts",s:"The documentary offered a strictly factual account."},
{w:"feckless",p:"adj",m:"lacking effectiveness or initiative",s:"The feckless manager avoided every hard decision."},
{w:"feeble",p:"adj",m:"weak",s:"His feeble excuse convinced no one."},
{w:"fester",p:"v",m:"to become worse through neglect",s:"The unresolved conflict festered for years."},
{w:"fickle",p:"adj",m:"changing frequently, especially in loyalty",s:"Public opinion can be remarkably fickle."},
{w:"fixate",p:"v",m:"to focus attention obsessively",s:"He fixated on the one negative comment."},
{w:"fleeting",p:"adj",m:"lasting only a short time",s:"The celebrity's fame was fleeting."},
{w:"flourish",p:"v",m:"to grow or develop successfully",s:"The business flourished after the rebrand."},
{w:"flout",p:"v",m:"to openly disregard a rule",s:"The driver flouted every traffic law in town."},
{w:"foreground",p:"v",m:"to bring into prominence",s:"The documentary foregrounds the workers' voices."},
{w:"foresight",p:"n",m:"the ability to anticipate future needs",s:"Her foresight saved the company millions."},
{w:"forestall",p:"v",m:"to prevent by acting in advance",s:"They forestalled the crisis with early repairs."},
{w:"forego",p:"v",m:"to go without; do without something",s:"She decided to forego dessert."},
{w:"forsake",p:"v",m:"to abandon or give up",s:"He refused to forsake his principles."},
{w:"fringe",p:"n",m:"the outer, less central part",s:"The fringe candidate had little chance of winning."},
{w:"frugality",p:"n",m:"the quality of being economical",s:"Her frugality let her retire a decade early."},
{w:"futile",p:"adj",m:"useless; producing no result",s:"Their attempts to stop the leak were futile."},
{w:"galvanize",p:"v",m:"to shock or excite into action",s:"The speech galvanized the crowd into protest."},
{w:"gawky",p:"adj",m:"awkward and clumsy, especially physically",s:"The gawky teenager tripped over his own feet."},
{w:"germane",p:"adj",m:"relevant to the matter at hand",s:"Please keep your comments germane to the topic."},
{w:"global",p:"adj",m:"relating to the whole world; comprehensive",s:"The company took a global approach to hiring."},
{w:"gloomy",p:"adj",m:"dark and depressing",s:"The forecast painted a gloomy picture for sales."},
{w:"gracious",p:"adj",m:"courteous and kind",s:"The host was gracious to every guest."},
{w:"gratify",p:"v",m:"to give pleasure or satisfaction",s:"The award gratified years of hard work."},
{w:"harbinger",p:"n",m:"a sign that something is coming",s:"The first robin is a harbinger of spring."},
{w:"harmonious",p:"adj",m:"free from conflict; pleasingly consistent",s:"They maintained a harmonious working relationship."},
{w:"heed",p:"v",m:"to pay attention to",s:"He failed to heed the storm warnings."},
{w:"herald",p:"v",m:"to signal the approach of",s:"Dark clouds heralded the coming storm."},
{w:"heterodox",p:"adj",m:"not conforming to accepted beliefs",s:"His heterodox economic views drew criticism."},
{w:"hidebound",p:"adj",m:"rigidly conservative and inflexible",s:"The hidebound committee rejected every new idea."},
{w:"hindrance",p:"n",m:"an obstacle",s:"The broken elevator was a major hindrance."},
{w:"homogeneity",p:"n",m:"the state of being uniform throughout",s:"The survey revealed surprising homogeneity in opinions."},
{w:"hortatory",p:"adj",m:"urging strongly to some course of action",s:"The coach gave a hortatory speech before the game."},
{w:"humdrum",p:"adj",m:"lacking excitement; dull",s:"He grew tired of his humdrum daily routine."},
{w:"hypocrite",p:"n",m:"a person who acts contrary to their stated beliefs",s:"Critics called the senator a hypocrite."},
{w:"iconoclastic",p:"adj",m:"attacking cherished beliefs or institutions",s:"The director's iconoclastic style shocked traditional critics."},
{w:"illiberal",p:"adj",m:"opposed to individual freedom; narrow-minded",s:"The regime imposed illiberal restrictions on the press."},
{w:"illuminate",p:"v",m:"to light up; to clarify",s:"Her essay illuminates a rarely discussed issue."},
{w:"imitate",p:"v",m:"to copy the actions or style of",s:"Young artists often imitate the masters first."},
{w:"imminent",p:"adj",m:"about to happen",s:"Forecasters warned that the storm was imminent."},
{w:"immunity",p:"n",m:"protection from something; resistance",s:"The vaccine provides strong immunity."},
{w:"impediment",p:"n",m:"an obstacle or hindrance",s:"Lack of funding was the main impediment to progress."},
{w:"impenetrable",p:"adj",m:"impossible to pass through or understand",s:"The legal jargon was nearly impenetrable."},
{w:"imperative",p:"adj",m:"extremely important; urgent",s:"It is imperative that we act now."},
{w:"impetuous",p:"adj",m:"acting suddenly without thought",s:"His impetuous decision cost him the contract."},
{w:"impetus",p:"n",m:"a driving force; stimulus",s:"The scandal gave impetus to reform efforts."},
{w:"impolitic",p:"adj",m:"not wise or sensible",s:"It was impolitic to criticize the boss publicly."},
{w:"improvisation",p:"n",m:"the act of creating spontaneously",s:"The jazz solo was pure improvisation."},
{w:"imprudent",p:"adj",m:"not sensible; rash",s:"Investing his savings in one stock was imprudent."},
{w:"impudence",p:"n",m:"bold disrespect",s:"The clerk's impudence surprised the manager."},
{w:"impulsive",p:"adj",m:"acting without forethought",s:"Her impulsive purchase drained her savings."},
{w:"inalienable",p:"adj",m:"unable to be taken away",s:"The declaration lists several inalienable rights."},
{w:"inarticulate",p:"adj",m:"unable to express oneself clearly",s:"He grew inarticulate when nervous."},
{w:"incendiary",p:"adj",m:"tending to provoke strong feeling",s:"The speech was full of incendiary rhetoric."},
{w:"inconsequential",p:"adj",m:"unimportant",s:"The typo was inconsequential to the overall argument."},
{w:"inconsiderable",p:"adj",m:"not significant in size or amount",s:"The savings were far from inconsiderable."},
{w:"indebted",p:"adj",m:"owing gratitude or money",s:"She felt indebted to her mentor for the opportunity."},
{w:"indecision",p:"n",m:"inability to make a decision",s:"His indecision cost the team valuable time."},
{w:"indecorous",p:"adj",m:"not in keeping with good taste",s:"His indecorous jokes offended several guests."},
{w:"indemnify",p:"v",m:"to compensate for loss or damage",s:"The policy indemnifies the owner against fire damage."},
{w:"indifferent",p:"adj",m:"having no particular interest",s:"He seemed indifferent to the outcome of the vote."},
{w:"indiscernible",p:"adj",m:"not able to be perceived",s:"The difference between the two shades was indiscernible."},
{w:"industrious",p:"adj",m:"hardworking and diligent",s:"The industrious apprentice finished early every day."},
{w:"inestimable",p:"adj",m:"too great to be measured",s:"Her contribution to the project was inestimable."},
{w:"infallible",p:"adj",m:"incapable of making mistakes",s:"No system is truly infallible."},
{w:"informed",p:"adj",m:"having relevant knowledge",s:"Voters should make an informed decision."},
{w:"ingenious",p:"adj",m:"cleverly inventive",s:"The engineer found an ingenious fix for the leak."},
{w:"inhibit",p:"v",m:"to hinder or restrain",s:"Fear of failure can inhibit creativity."},
{w:"injudicious",p:"adj",m:"showing poor judgment",s:"His injudicious comment nearly ended the negotiation."},
{w:"inscrutable",p:"adj",m:"impossible to understand or interpret",s:"Her inscrutable expression gave nothing away."},
{w:"insightful",p:"adj",m:"showing deep understanding",s:"The reviewer offered an insightful critique."},
{w:"insolence",p:"n",m:"bold disrespect",s:"The teacher wouldn't tolerate such insolence."},
{w:"integrate",p:"v",m:"to combine parts into a whole",s:"The new software integrates with existing tools."},
{w:"intelligible",p:"adj",m:"able to be understood",s:"His mumbled explanation was barely intelligible."},
{w:"interchangeable",p:"adj",m:"able to be exchanged without difference",s:"The two parts are fully interchangeable."},
{w:"intermediary",p:"n",m:"a person who acts as a link between parties",s:"A lawyer served as intermediary during the talks."},
{w:"interminable",p:"adj",m:"endless, especially tediously so",s:"The meeting felt interminable by the third hour."},
{w:"interweave",p:"v",m:"to weave together; combine",s:"The novel interweaves two storylines across decades."},
{w:"intimately",p:"adv",m:"in a close, personal manner",s:"She was intimately familiar with the old building's history."},
{w:"intrigue",p:"v",m:"to arouse curiosity",s:"The unsolved case intrigued detectives for years."},
{w:"intrinsic",p:"adj",m:"belonging naturally; essential",s:"The painting has intrinsic value beyond its price."},
{w:"invaluable",p:"adj",m:"extremely useful",s:"Her advice proved invaluable during the crisis."},
{w:"invigorate",p:"v",m:"to give energy or strength to",s:"The cold morning air invigorated the runners."},
{w:"involved",p:"adj",m:"complicated; deeply engaged",s:"The plot became increasingly involved by the final act."},
{w:"irrational",p:"adj",m:"not logical",s:"His fear of the number thirteen is irrational."},
{w:"irksome",p:"adj",m:"annoying",s:"The constant buzzing was irksome all afternoon."},
{w:"ironic",p:"adj",m:"happening contrary to expectation",s:"It was ironic that the fire station burned down."},
{w:"irrefutable",p:"adj",m:"impossible to deny or disprove",s:"The DNA evidence was irrefutable."},
{w:"irredeemable",p:"adj",m:"impossible to save or reform",s:"The old bridge was deemed irredeemable and torn down."},
{w:"irresolute",p:"adj",m:"unsure how to act; hesitant",s:"The irresolute manager delayed the decision for weeks."},
{w:"jettison",p:"v",m:"to discard something no longer needed",s:"The startup jettisoned its original business plan."},
{w:"juxtaposition",p:"n",m:"placing things side by side for contrast",s:"The exhibit relies on juxtaposition of old and new."},
{w:"keen",p:"adj",m:"having sharp perception; eager",s:"She has a keen eye for detail."},
{w:"kindred",p:"adj",m:"similar in kind; related",s:"They felt like kindred spirits from the start."},
{w:"laborious",p:"adj",m:"requiring great effort",s:"Restoring the mural was a laborious process."},
{w:"latitude",p:"n",m:"freedom of action or choice",s:"The new manager gave employees more latitude."},
{w:"laudable",p:"adj",m:"deserving praise",s:"Her effort to help was laudable, even if it failed."},
{w:"lax",p:"adj",m:"not strict; careless",s:"Security at the gate was surprisingly lax."},
{w:"layperson",p:"n",m:"a person without professional expertise in a field",s:"The article explains the ruling for the average layperson."},
{w:"lionize",p:"v",m:"to treat as a celebrity",s:"The press lionized the young inventor."},
{w:"long-winded",p:"adj",m:"tediously lengthy in speech or writing",s:"His long-winded introduction lost the audience."},
{w:"lure",p:"v",m:"to tempt or attract",s:"Discounts lured shoppers into the store."},
{w:"lurid",p:"adj",m:"shockingly vivid or sensational",s:"The tabloid printed lurid details of the scandal."},
{w:"magnanimity",p:"n",m:"generosity, especially toward a rival",s:"His magnanimity in defeat impressed everyone."},
{w:"makeshift",p:"adj",m:"temporary and improvised",s:"They built a makeshift shelter from tarps."},
{w:"maladroit",p:"adj",m:"clumsy; lacking skill",s:"His maladroit apology only made things worse."},
{w:"malign",p:"v",m:"to speak badly of",s:"Her critics maligned her in the press."},
{w:"malignant",p:"adj",m:"harmful; likely to cause death",s:"The tumor was found to be malignant."},
{w:"manacle",p:"n",m:"a restraint for the hands",s:"The prisoner's manacles were removed before the trial."},
{w:"manipulate",p:"v",m:"to control or influence cleverly, often unfairly",s:"He manipulated the data to fit his conclusion."},
{w:"marginalize",p:"v",m:"to push to the edges of society or importance",s:"The policy further marginalized rural communities."},
{w:"mask",p:"v",m:"to conceal or disguise",s:"Perfume couldn't mask the smell of smoke."},
{w:"materialize",p:"v",m:"to become actual or real",s:"The promised funding never materialized."},
{w:"meager",p:"adj",m:"small in amount; insufficient",s:"They survived on a meager harvest that year."},
{w:"meld",p:"v",m:"to blend or merge",s:"The chef melds French and Thai flavors."},
{w:"menace",p:"n",m:"a threat or danger",s:"The escaped animal was a menace to the town."},
{w:"mimic",p:"v",m:"to imitate closely",s:"The parrot could mimic almost any sound."},
{w:"misnomer",p:"n",m:"a wrong or inaccurate name",s:"'Silent film' is a misnomer since they had live music."},
{w:"modish",p:"adj",m:"fashionable",s:"The boutique sold modish accessories."},
{w:"monotony",p:"n",m:"lack of variety; tedious sameness",s:"The monotony of the assembly line wore him down."},
{w:"morbid",p:"adj",m:"having an unhealthy interest in death or unpleasant things",s:"He had a morbid fascination with true crime."},
{w:"mortify",p:"v",m:"to cause great embarrassment",s:"Tripping on stage mortified her for weeks."},
{w:"mounting",p:"adj",m:"steadily increasing",s:"The company faced mounting debt."},
{w:"multifaceted",p:"adj",m:"having many aspects",s:"The issue is more multifaceted than it first appears."},
{w:"murky",p:"adj",m:"dark and unclear",s:"The pond's murky water hid the fish below."},
{w:"naive",p:"adj",m:"lacking experience or judgment",s:"It was naive to trust the stranger's promise."},
{w:"narcissism",p:"n",m:"excessive self-admiration",s:"His narcissism made teamwork nearly impossible."},
{w:"narrative",p:"n",m:"a spoken or written account of events",s:"The film tells its narrative out of order."},
{w:"nascent",p:"adj",m:"just beginning to develop",s:"The nascent industry attracted early investors."},
{w:"nettle",p:"v",m:"to irritate or annoy",s:"The comment nettled him more than he admitted."},
{w:"normative",p:"adj",m:"establishing a standard or norm",s:"The paper takes a normative stance on the issue."},
{w:"novel",p:"adj",m:"new and original",s:"They proposed a novel solution to the traffic problem."},
{w:"noxious",p:"adj",m:"harmful or poisonous",s:"Noxious fumes forced the evacuation of the building."},
{w:"object",p:"v",m:"to express disapproval or opposition",s:"The lawyer objected to the surprise witness."},
{w:"obligate",p:"v",m:"to bind legally or morally",s:"The contract obligates the tenant to pay by the fifth."},
{w:"obscure",p:"adj",m:"not well known; unclear",s:"He cited an obscure regulation to justify the delay."},
{w:"obsolete",p:"adj",m:"no longer in use; outdated",s:"The old software became obsolete within a year."},
{w:"obviate",p:"v",m:"to remove a need or difficulty in advance",s:"The new policy obviates the need for extra paperwork."},
{w:"omnipresent",p:"adj",m:"present everywhere at once",s:"Cameras felt almost omnipresent in the city center."},
{w:"omniscient",p:"adj",m:"knowing everything",s:"The novel is told from an omniscient narrator's view."},
{w:"opportunism",p:"n",m:"taking advantage of circumstances without regard to principle",s:"Critics accused the politician of pure opportunism."},
{w:"optimistic",p:"adj",m:"hopeful about the future",s:"She remained optimistic despite the setback."},
{w:"original",p:"adj",m:"not copied; the first of its kind",s:"The gallery only displays original artwork."},
{w:"outmoded",p:"adj",m:"no longer fashionable or useful",s:"The factory relied on outmoded equipment."},
{w:"overly",p:"adv",m:"excessively",s:"He was overly cautious about the small risk."},
{w:"overshadow",p:"v",m:"to make less important by comparison",s:"Her achievement was overshadowed by the scandal."},
{w:"overstate",p:"v",m:"to exaggerate",s:"The report overstated the project's success."},
{w:"panache",p:"n",m:"flamboyant confidence of style",s:"She delivered the toast with real panache."},
{w:"partial",p:"adj",m:"biased; incomplete",s:"The referee was accused of being partial to the home team."},
{w:"passable",p:"adj",m:"just adequate; able to be traveled",s:"His French was passable, if not fluent."},
{w:"pastoral",p:"adj",m:"relating to peaceful rural life",s:"The painting shows a pastoral scene of grazing sheep."},
{w:"patent",p:"adj",m:"obvious; clearly visible",s:"It was patent that the plan would fail."},
{w:"peculiarity",p:"n",m:"a distinctive or odd feature",s:"Every old house has its own peculiarities."},
{w:"pedestrian",p:"adj",m:"lacking excitement; ordinary",s:"The film's plot was frankly pedestrian."},
{w:"pejorative",p:"adj",m:"expressing contempt or disapproval",s:"The word was once neutral but is now pejorative."},
{w:"penetrate",p:"v",m:"to pass into or through",s:"Sunlight barely penetrated the dense forest canopy."},
{w:"penitent",p:"adj",m:"feeling regret for wrongdoing",s:"The penitent employee apologized to the whole team."},
{w:"peripheral",p:"adj",m:"relating to the outer edge; of minor importance",s:"That detail is peripheral to the main argument."},
{w:"perseverance",p:"n",m:"persistence despite difficulty",s:"Her perseverance eventually paid off."},
{w:"persistent",p:"adj",m:"continuing firmly despite difficulty",s:"His persistent questioning finally got an answer."},
{w:"personify",p:"v",m:"to represent an abstract quality as a person",s:"The statue personifies justice."},
{w:"perspicacity",p:"n",m:"keenness of insight",s:"Her perspicacity impressed the entire panel."},
{w:"pessimism",p:"n",m:"a tendency to expect the worst",s:"His pessimism made the team hesitant to try new ideas."},
{w:"picturesque",p:"adj",m:"visually charming or quaint",s:"The picturesque village drew tourists year-round."},
{w:"pithy",p:"adj",m:"concise and forceful in expression",s:"Her pithy remark summed up the debate perfectly."},
{w:"pivotal",p:"adj",m:"of crucial importance",s:"That meeting was pivotal to the company's future."},
{w:"plastic",p:"adj",m:"easily shaped or molded; adaptable",s:"Young minds are remarkably plastic."},
{w:"plod",p:"v",m:"to walk slowly and heavily; work laboriously",s:"He plodded through the last chapters of the textbook."},
{w:"polemic",p:"n",m:"a strong verbal or written attack",s:"His essay was more polemic than analysis."},
{w:"portend",p:"v",m:"to be a sign that something will happen",s:"Dark skies portended a rough voyage."},
{w:"pragmatism",p:"n",m:"a practical approach to problems",s:"Her pragmatism made her a valuable negotiator."},
{w:"precedence",p:"n",m:"the condition of being given priority",s:"Safety takes precedence over speed."},
{w:"predominant",p:"adj",m:"main or strongest",s:"English is the predominant language of business there."},
{w:"preeminent",p:"adj",m:"surpassing all others; leading",s:"He is a preeminent scholar in his field."},
{w:"premonition",p:"n",m:"a strong feeling that something is about to happen",s:"She had a premonition before the accident."},
{w:"prescient",p:"adj",m:"having knowledge of events before they happen",s:"His prescient warning about the market went unheeded."},
{w:"pressing",p:"adj",m:"requiring immediate attention",s:"They had a pressing need for more funding."},
{w:"presume",p:"v",m:"to suppose to be true without proof",s:"I presume you've already read the report."},
{w:"prevalent",p:"adj",m:"widespread; common",s:"The disease is more prevalent in urban areas."},
{w:"promulgate",p:"v",m:"to promote or make widely known officially",s:"The agency promulgated new safety rules."},
{w:"propagate",p:"v",m:"to spread or reproduce",s:"Rumors propagate quickly on social media."},
{w:"prop up",p:"v",m:"to support, often artificially",s:"Subsidies were used to prop up the failing industry."},
{w:"punctilious",p:"adj",m:"very attentive to detail and correct behavior",s:"He was punctilious about following every rule."},
{w:"puzzle",p:"v",m:"to confuse; leave uncertain",s:"The strange symbol puzzled archaeologists for decades."},
{w:"quotidian",p:"adj",m:"everyday; ordinary",s:"The novel finds beauty in quotidian routines."},
{w:"rally",p:"v",m:"to come together in support; to recover",s:"Fans rallied behind the injured player."},
{w:"rationalize",p:"v",m:"to justify with logical reasons, often after the fact",s:"He rationalized the purchase as a necessary expense."},
{w:"redemption",p:"n",m:"the act of being saved or making amends",s:"The film is a story of redemption and forgiveness."},
{w:"redouble",p:"v",m:"to greatly increase efforts",s:"They redoubled their efforts after the setback."},
{w:"refuge",p:"n",m:"a place providing shelter or protection",s:"The old church became a refuge for the homeless."},
{w:"rein in",p:"v",m:"to restrain or control",s:"The bank moved to rein in risky lending."},
{w:"replicate",p:"v",m:"to reproduce or copy exactly",s:"Other labs failed to replicate the surprising result."},
{w:"residual",p:"adj",m:"remaining after most has gone",s:"There was still residual doubt about the plan."},
{w:"resolute",p:"adj",m:"firm and determined",s:"She remained resolute despite the criticism."},
{w:"restive",p:"adj",m:"restless and difficult to control",s:"The restive crowd grew impatient waiting for news."},
{w:"restrain",p:"v",m:"to hold back or control",s:"Security had to restrain the unruly fan."},
{w:"rhapsody",p:"n",m:"an effusive expression of enthusiasm",s:"He launched into a rhapsody about his hometown."},
{w:"ridicule",p:"v",m:"to mock or make fun of",s:"Classmates ridiculed his unusual accent."},
{w:"ruminate",p:"v",m:"to think deeply about something",s:"She ruminated on the decision for days."},
{w:"salubrious",p:"adj",m:"health-giving; beneficial",s:"They moved to the coast for its salubrious climate."},
{w:"scathing",p:"adj",m:"harshly critical",s:"The critic wrote a scathing review of the play."},
{w:"schism",p:"n",m:"a split between strongly opposed groups",s:"The disagreement caused a schism within the party."},
{w:"scintillating",p:"adj",m:"brilliantly clever or lively",s:"Her scintillating wit made her a popular guest."},
{w:"scrutinize",p:"v",m:"to examine closely",s:"Auditors scrutinized every line of the budget."},
{w:"scuffle",p:"n",m:"a short, confused fight",s:"A scuffle broke out near the exit."},
{w:"self-righteous",p:"adj",m:"convinced of one's own moral superiority",s:"His self-righteous tone alienated potential allies."},
{w:"shrewd",p:"adj",m:"having sharp practical judgment",s:"Her shrewd bargaining saved the company thousands."},
{w:"sinister",p:"adj",m:"suggesting evil or harm",s:"A sinister figure lurked near the entrance."},
{w:"skittish",p:"adj",m:"nervous and easily startled",s:"The skittish horse bolted at the loud noise."},
{w:"slight",p:"v",m:"to insult by treating as unimportant",s:"She felt slighted when her idea was ignored."},
{w:"staunch",p:"adj",m:"firm and loyal in support",s:"He remained a staunch defender of the policy."},
{w:"staple",p:"n",m:"a main or basic element",s:"Rice is a dietary staple in much of Asia."},
{w:"startling",p:"adj",m:"surprising in a sudden, striking way",s:"The results were startling to the research team."},
{w:"stingy",p:"adj",m:"unwilling to spend or give",s:"He was too stingy to leave a tip."},
{w:"stunned",p:"adj",m:"shocked into silence or confusion",s:"The audience was stunned by the twist ending."},
{w:"substantiate",p:"v",m:"to provide evidence to support a claim",s:"The lawyer failed to substantiate the accusation."},
{w:"subvert",p:"v",m:"to undermine the power of an established system",s:"The leak was meant to subvert public trust."},
{w:"sullen",p:"adj",m:"gloomily silent or resentful",s:"The teenager gave a sullen shrug and left."},
{w:"supplement",p:"v",m:"to add to in order to improve or complete",s:"She supplemented her income with freelance work."},
{w:"supplication",p:"n",m:"the act of asking humbly for something",s:"His letter was written as a supplication for mercy."},
{w:"surly",p:"adj",m:"bad-tempered and unfriendly",s:"The surly clerk barely acknowledged customers."},
{w:"synoptic",p:"adj",m:"giving a general summary or overview",s:"The report offers a synoptic view of the industry."},
{w:"syntactical",p:"adj",m:"relating to sentence structure",s:"The essay had several syntactical errors."},
{w:"tactless",p:"adj",m:"lacking sensitivity in dealing with others",s:"His tactless joke ruined the toast."},
{w:"tendentious",p:"adj",m:"biased toward a particular point of view",s:"The article was widely criticized as tendentious."},
{w:"transcend",p:"v",m:"to go beyond the limits of",s:"Great art transcends language barriers."},
{w:"transgression",p:"n",m:"an act that violates a rule",s:"His minor transgression cost him the promotion."},
{w:"transitory",p:"adj",m:"not permanent; brief",s:"Fame in that field is often transitory."},
{w:"trifle",p:"n",m:"something of little value or importance",s:"Don't worry over such a small trifle."},
{w:"uncultivated",p:"adj",m:"not developed or refined; not farmed",s:"The land remained uncultivated for decades."},
{w:"undemonstrative",p:"adj",m:"not openly showing emotion",s:"He was undemonstrative even at his own wedding."},
{w:"underscore",p:"v",m:"to emphasize",s:"The report underscores the need for reform."},
{w:"understated",p:"adj",m:"presented in a subtle, restrained way",s:"Her understated elegance impressed the judges."},
{w:"undo",p:"v",m:"to reverse or cancel",s:"One mistake nearly undid years of progress."},
{w:"unprecedented",p:"adj",m:"never done or known before",s:"The storm caused unprecedented flooding."},
{w:"unpremeditated",p:"adj",m:"not planned in advance",s:"The court ruled the act was unpremeditated."},
{w:"unpretentious",p:"adj",m:"modest; not showy",s:"The chef kept the unpretentious little diner open for decades."},
{w:"untapped",p:"adj",m:"not yet used or exploited",s:"The region has untapped potential for tourism."},
{w:"utterly",p:"adv",m:"completely",s:"The plan was utterly unrealistic."},
{w:"venal",p:"adj",m:"easily bribed or corrupted",s:"The venal official accepted bribes for years."},
{w:"vindicated",p:"adj",m:"cleared of blame or suspicion",s:"She felt vindicated when the results confirmed her theory."},
{w:"virulence",p:"n",m:"extreme harmfulness or bitterness",s:"The virulence of the outbreak alarmed health officials."},
{w:"voluble",p:"adj",m:"talking fluently and at length",s:"The voluble guide never paused between facts."},
{w:"witty",p:"adj",m:"showing quick, clever humor",s:"Her witty remarks kept the dinner lively."},
{w:"woo",p:"v",m:"to try to gain the favor or love of",s:"The company wooed top talent with generous offers."},
{w:"zealot",p:"n",m:"a person fanatically devoted to a cause",s:"The zealot refused to consider any compromise."}
];
